/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package codigo;

import static codigo.Home.JP_content;
import java.awt.BorderLayout;
import java.sql.*;
import javax.swing.JOptionPane;

public class ActualizarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form ActualizarUsuario
     */
    public ActualizarUsuario() {
        initComponents();
        txtPrimerNombre.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        txtPrimerNombre = new javax.swing.JTextField();
        Text4 = new javax.swing.JLabel();
        txtPrimerApellido = new javax.swing.JTextField();
        Text2 = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        Text1 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        Text5 = new javax.swing.JLabel();
        txtSegundoApellido = new javax.swing.JTextField();
        Text6 = new javax.swing.JLabel();
        txtSegundoNombre = new javax.swing.JTextField();
        Text7 = new javax.swing.JLabel();
        txtDomicilio1 = new javax.swing.JTextField();
        btn_Actualizar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Editar Usuario");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Primer nombre");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtPrimerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerNombreActionPerformed(evt);
            }
        });
        add(txtPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, -1));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("Primer apellido");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerApellidoActionPerformed(evt);
            }
        });
        add(txtPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 230, -1));

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text2.setText("Domicilio");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomicilioActionPerformed(evt);
            }
        });
        add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 230, -1));

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text1.setText("Teléfono");
        add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 230, -1));

        Text5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text5.setText("Segundo apellido");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        txtSegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegundoApellidoActionPerformed(evt);
            }
        });
        add(txtSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 230, -1));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Segundo nombre");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        txtSegundoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegundoNombreActionPerformed(evt);
            }
        });
        add(txtSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 230, -1));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Devoluciones extratemporales");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        txtDomicilio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomicilio1ActionPerformed(evt);
            }
        });
        add(txtDomicilio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 230, -1));

        btn_Actualizar.setBackground(new java.awt.Color(54, 33, 89));
        btn_Actualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Actualizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.setBorderPainted(false);
        btn_Actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });
        add(btn_Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 90, 40));

        btnVolver.setBackground(new java.awt.Color(54, 33, 89));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorderPainted(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 90, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerNombreActionPerformed

    private void txtPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerApellidoActionPerformed

    private void txtDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomicilioActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtSegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegundoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundoApellidoActionPerformed

    private void txtSegundoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegundoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundoNombreActionPerformed

    private void txtDomicilio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomicilio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomicilio1ActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        String primerNombre = txtPrimerNombre.getText();
        String segundoNombre = txtSegundoNombre.getText();
        String primerApellido = txtPrimerApellido.getText();
        String segundoApellido = txtSegundoApellido.getText();
        String Direccion = txtDomicilio.getText();
        int Telefono = Integer.parseInt(txtTelefono.getText());

        try{
            Connection con = Conexion.getConnection();
            PreparedStatement ps = con.prepareStatement("INSERT INTO Usuarios (PrimerNombre,SegundoNombre,PrimerApellido, SegundoApellido, Direccion, Telefono, DevolucionesExtratemporales) VALUES (?,?,?,?,?,?,?)");
            ps.setString(1, primerNombre);
            ps.setString(2, segundoNombre);
            ps.setString(3, primerApellido);
            ps.setString(4, segundoApellido);
            ps.setString(5, Direccion);
            ps.setInt(6, Telefono);
            ps.setShort(7, (short)0);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Usuario editado exitosamente");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error: " + ex.toString());
        }
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // Abrir sección
        Usuarios p1 = new Usuarios();
        p1.setSize(750, 430);
        p1.setLocation(0,0);

        JP_content.removeAll();
        JP_content.add(p1, BorderLayout.CENTER);
        JP_content.revalidate();
        JP_content.repaint();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtDomicilio1;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtSegundoApellido;
    private javax.swing.JTextField txtSegundoNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}


/*
Statement stm = reg.createStatement();
                    stm.executeUpdate("UPDATE Usuarios SET ContactName = 'Alfred Schmidt', City= 'Frankfurt' WHERE CustomerID = "+valorID);
                    javax.swing.JOptionPane.showMessageDialog(this, "¡Usuario editado! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    cargarTabla();
*/