/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package codigo;

/**
 *
 * @author juanp
 */
public class Devoluciones extends javax.swing.JPanel {

    /**
     * Creates new form Devoluciones
     */
    public Devoluciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        idUsuario = new javax.swing.JTextField();
        IdLibro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Text3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(640, 390));
        setPreferredSize(new java.awt.Dimension(640, 390));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Devolución de Libro");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text2.setText("Id Usuario");
        jPanel1.add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        idUsuario.setForeground(new java.awt.Color(102, 102, 102));
        idUsuario.setText("Ingrese el id del usuario");
        idUsuario.setBorder(null);
        idUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idUsuarioMousePressed(evt);
            }
        });
        jPanel1.add(idUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 260, 30));

        IdLibro.setForeground(new java.awt.Color(102, 102, 102));
        IdLibro.setText("Ingrese el id del Libro a devolver");
        IdLibro.setBorder(null);
        IdLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IdLibroMousePressed(evt);
            }
        });
        IdLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdLibroActionPerformed(evt);
            }
        });
        jPanel1.add(IdLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 260, 30));

        jButton1.setBackground(new java.awt.Color(54, 33, 89));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Devolver");
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 90, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libros-removebg.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 270, 280));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 10, 350));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Libro ID");
        jPanel1.add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void idUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idUsuarioMousePressed
        if(idUsuario.getText().equals("Ingrese el id del usuario"))
        idUsuario.setText("");
        if(IdLibro.getText().equals("") || IdLibro.getText() == null || IdLibro.getText().equals(" "))
        IdLibro.setText("Ingrese el id del Libro a devolver");
    }//GEN-LAST:event_idUsuarioMousePressed

    private void IdLibroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdLibroMousePressed
        if(IdLibro.getText().equals("Ingrese el id del Libro a devolver"))
        IdLibro.setText("");
        if(idUsuario.getText().equals("") || idUsuario.getText() == null || idUsuario.getText().equals(" "))
        idUsuario.setText("Ingrese el id del usuario");
    }//GEN-LAST:event_IdLibroMousePressed

    private void IdLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdLibroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdLibro;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Title;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField idUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
