/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codigo;

import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;

/**
 *
 * @author juanp
 */
public class Home extends javax.swing.JFrame {

    int xMouse, yMouse;
    public Home() {
        initComponents();
        //this.setIconImage(delete-sign.png);
        this.setLocationRelativeTo(null);
        
         
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"," ;Septiembre"
            ,"Octubre","Noviembre","Diciemrbre"};
        fecha.setText("Hoy es "+dia+" de "+meses[month - 1]+" de "+year);
        
        Bienvenida b1 = new Bienvenida();
        b1.setSize(750, 430);
        b1.setLocation(0,0);
        
        JP_content.removeAll();
        JP_content.add(b1, BorderLayout.CENTER);
        JP_content.revalidate();
        JP_content.repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        JP_content = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        JPbtn_home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JPbtn_Devoluciones = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JPbtn_Usuarios = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JPbtn_Libros = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        JPbtn_Reportes = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        JPbtn_Prestamos = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        JP_Header = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();
        Titulo = new javax.swing.JPanel();
        JP_exit = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JP_content.setMaximumSize(new java.awt.Dimension(750, 430));
        JP_content.setMinimumSize(new java.awt.Dimension(750, 430));

        javax.swing.GroupLayout JP_contentLayout = new javax.swing.GroupLayout(JP_content);
        JP_content.setLayout(JP_contentLayout);
        JP_contentLayout.setHorizontalGroup(
            JP_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        JP_contentLayout.setVerticalGroup(
            JP_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        bg.add(JP_content, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 710, 390));

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nadino collections");
        sidePanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        sidePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 210, 10));

        JPbtn_home.setBackground(new java.awt.Color(85, 55, 118));
        JPbtn_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPbtn_home.setPreferredSize(new java.awt.Dimension(259, 60));
        JPbtn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPbtn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPbtn_homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPbtn_homeMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home-outline.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pagina principal");

        javax.swing.GroupLayout JPbtn_homeLayout = new javax.swing.GroupLayout(JPbtn_home);
        JPbtn_home.setLayout(JPbtn_homeLayout);
        JPbtn_homeLayout.setHorizontalGroup(
            JPbtn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPbtn_homeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        JPbtn_homeLayout.setVerticalGroup(
            JPbtn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(JPbtn_homeLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(JPbtn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        sidePanel.add(JPbtn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 60));

        JPbtn_Devoluciones.setBackground(new java.awt.Color(63, 43, 100));
        JPbtn_Devoluciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPbtn_Devoluciones.setPreferredSize(new java.awt.Dimension(259, 60));
        JPbtn_Devoluciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPbtn_DevolucionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPbtn_DevolucionesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPbtn_DevolucionesMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-hoy-24.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Devoluciones");

        javax.swing.GroupLayout JPbtn_DevolucionesLayout = new javax.swing.GroupLayout(JPbtn_Devoluciones);
        JPbtn_Devoluciones.setLayout(JPbtn_DevolucionesLayout);
        JPbtn_DevolucionesLayout.setHorizontalGroup(
            JPbtn_DevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPbtn_DevolucionesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        JPbtn_DevolucionesLayout.setVerticalGroup(
            JPbtn_DevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPbtn_DevolucionesLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(JPbtn_DevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        sidePanel.add(JPbtn_Devoluciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        JPbtn_Usuarios.setBackground(new java.awt.Color(63, 43, 100));
        JPbtn_Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPbtn_Usuarios.setPreferredSize(new java.awt.Dimension(260, 60));
        JPbtn_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPbtn_UsuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPbtn_UsuariosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPbtn_UsuariosMousePressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-grupo-de-usuario-24.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Usuarios");

        javax.swing.GroupLayout JPbtn_UsuariosLayout = new javax.swing.GroupLayout(JPbtn_Usuarios);
        JPbtn_Usuarios.setLayout(JPbtn_UsuariosLayout);
        JPbtn_UsuariosLayout.setHorizontalGroup(
            JPbtn_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPbtn_UsuariosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        JPbtn_UsuariosLayout.setVerticalGroup(
            JPbtn_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPbtn_UsuariosLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(JPbtn_UsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        sidePanel.add(JPbtn_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 260, -1));

        JPbtn_Libros.setBackground(new java.awt.Color(63, 43, 100));
        JPbtn_Libros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPbtn_Libros.setPreferredSize(new java.awt.Dimension(260, 60));
        JPbtn_Libros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPbtn_LibrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPbtn_LibrosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPbtn_LibrosMousePressed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book-open-page-variant.png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Libros");

        javax.swing.GroupLayout JPbtn_LibrosLayout = new javax.swing.GroupLayout(JPbtn_Libros);
        JPbtn_Libros.setLayout(JPbtn_LibrosLayout);
        JPbtn_LibrosLayout.setHorizontalGroup(
            JPbtn_LibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPbtn_LibrosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        JPbtn_LibrosLayout.setVerticalGroup(
            JPbtn_LibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPbtn_LibrosLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(JPbtn_LibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        sidePanel.add(JPbtn_Libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 260, -1));

        JPbtn_Reportes.setBackground(new java.awt.Color(63, 43, 100));
        JPbtn_Reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPbtn_Reportes.setPreferredSize(new java.awt.Dimension(242, 60));
        JPbtn_Reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPbtn_ReportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPbtn_ReportesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPbtn_ReportesMousePressed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/file-chart.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Reportes");

        javax.swing.GroupLayout JPbtn_ReportesLayout = new javax.swing.GroupLayout(JPbtn_Reportes);
        JPbtn_Reportes.setLayout(JPbtn_ReportesLayout);
        JPbtn_ReportesLayout.setHorizontalGroup(
            JPbtn_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPbtn_ReportesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        JPbtn_ReportesLayout.setVerticalGroup(
            JPbtn_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPbtn_ReportesLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(JPbtn_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        sidePanel.add(JPbtn_Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 260, -1));

        JPbtn_Prestamos.setBackground(new java.awt.Color(63, 43, 100));
        JPbtn_Prestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPbtn_Prestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JPbtn_PrestamosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JPbtn_PrestamosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JPbtn_PrestamosMousePressed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-calendario-más-24.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Prestamos");

        javax.swing.GroupLayout JPbtn_PrestamosLayout = new javax.swing.GroupLayout(JPbtn_Prestamos);
        JPbtn_Prestamos.setLayout(JPbtn_PrestamosLayout);
        JPbtn_PrestamosLayout.setHorizontalGroup(
            JPbtn_PrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPbtn_PrestamosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        JPbtn_PrestamosLayout.setVerticalGroup(
            JPbtn_PrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPbtn_PrestamosLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(JPbtn_PrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        sidePanel.add(JPbtn_Prestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 60));

        bg.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 570));

        JP_Header.setBackground(new java.awt.Color(122, 72, 221));

        fecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("Hoy es Sábado 28 de Abril de 2018");

        javax.swing.GroupLayout JP_HeaderLayout = new javax.swing.GroupLayout(JP_Header);
        JP_Header.setLayout(JP_HeaderLayout);
        JP_HeaderLayout.setHorizontalGroup(
            JP_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_HeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(fecha)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        JP_HeaderLayout.setVerticalGroup(
            JP_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_HeaderLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        bg.add(JP_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 710, 150));

        Titulo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TituloMouseDragged(evt);
            }
        });
        Titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TituloMousePressed(evt);
            }
        });

        JP_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JP_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JP_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JP_exitMouseExited(evt);
            }
        });

        exit.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        exit.setText(" X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout JP_exitLayout = new javax.swing.GroupLayout(JP_exit);
        JP_exit.setLayout(JP_exitLayout);
        JP_exitLayout.setHorizontalGroup(
            JP_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );
        JP_exitLayout.setVerticalGroup(
            JP_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_exitLayout.createSequentialGroup()
                .addComponent(exit)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TituloLayout.createSequentialGroup()
                .addGap(0, 942, Short.MAX_VALUE)
                .addComponent(JP_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
         System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void JPbtn_PrestamosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_PrestamosMousePressed
        // Abrir sección
        setColor(JPbtn_Prestamos);
        resetColor(JPbtn_home);
        resetColor(JPbtn_Devoluciones);
        resetColor(JPbtn_Usuarios);
        resetColor(JPbtn_Libros);
        resetColor(JPbtn_Reportes);
        
        Prestamos p1 = new Prestamos();
        p1.setSize(750, 430);
        p1.setLocation(0,0);
        
        JP_content.removeAll();
        JP_content.add(p1, BorderLayout.CENTER);
        JP_content.revalidate();
        JP_content.repaint();
    }//GEN-LAST:event_JPbtn_PrestamosMousePressed

    private void JPbtn_homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_homeMousePressed
        setColor(JPbtn_home);
        resetColor(JPbtn_Prestamos);
        resetColor(JPbtn_Devoluciones);
        resetColor(JPbtn_Usuarios);
        resetColor(JPbtn_Libros);
        resetColor(JPbtn_Reportes);

        // Abrir sección
        Bienvenida b1 = new Bienvenida();
        b1.setSize(750, 430);
        b1.setLocation(0,0);
        
        JP_content.removeAll();
        JP_content.add(b1, BorderLayout.CENTER);
        JP_content.revalidate();
        JP_content.repaint();
    }//GEN-LAST:event_JPbtn_homeMousePressed

    private void JPbtn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_homeMouseEntered
        setColor(JPbtn_home);
        /*
        if(JPbtn_home.getBackground().getRGB() == -15574355)
            setColor(JPbtn_home);
        */
    }//GEN-LAST:event_JPbtn_homeMouseEntered

    private void JPbtn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_homeMouseExited
        resetColor(JPbtn_home);
        /*
        if(JPbtn_Prestamos.getBackground().getRGB() != -15574355 || JPbtn_Devoluciones.getBackground().getRGB() != -15574355
            || JPbtn_Usuarios.getBackground().getRGB() != -15574355 || JPbtn_Libros.getBackground().getRGB() != -15574355 || JPbtn_Reportes.getBackground().getRGB() != -15574355)
            resetColor(JPbtn_home);
        */
    }//GEN-LAST:event_JPbtn_homeMouseExited

    private void JPbtn_DevolucionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_DevolucionesMouseEntered
        setColor(JPbtn_Devoluciones);
    }//GEN-LAST:event_JPbtn_DevolucionesMouseEntered

    private void JPbtn_DevolucionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_DevolucionesMouseExited
        resetColor(JPbtn_Devoluciones);
    }//GEN-LAST:event_JPbtn_DevolucionesMouseExited

    private void JPbtn_DevolucionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_DevolucionesMousePressed
        setColor(JPbtn_Devoluciones);
        resetColor(JPbtn_Prestamos);
        resetColor(JPbtn_home);
        resetColor(JPbtn_Usuarios);
        resetColor(JPbtn_Libros);
        resetColor(JPbtn_Reportes);

        // Abrir sección
        Devoluciones b1 = new Devoluciones();
        b1.setSize(750, 430);
        b1.setLocation(0,0);
        
        JP_content.removeAll();
        JP_content.add(b1, BorderLayout.CENTER);
        JP_content.revalidate();
        JP_content.repaint();
    }//GEN-LAST:event_JPbtn_DevolucionesMousePressed

    private void JPbtn_PrestamosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_PrestamosMouseEntered
        setColor(JPbtn_Prestamos);
    }//GEN-LAST:event_JPbtn_PrestamosMouseEntered

    private void JPbtn_PrestamosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_PrestamosMouseExited
        resetColor(JPbtn_Prestamos);
    }//GEN-LAST:event_JPbtn_PrestamosMouseExited

    private void JPbtn_UsuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_UsuariosMouseExited
        resetColor(JPbtn_Usuarios);
    }//GEN-LAST:event_JPbtn_UsuariosMouseExited

    private void JPbtn_UsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_UsuariosMouseEntered
        setColor(JPbtn_Usuarios);
    }//GEN-LAST:event_JPbtn_UsuariosMouseEntered

    private void JPbtn_UsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_UsuariosMousePressed
        setColor(JPbtn_Usuarios);
        resetColor(JPbtn_Prestamos);
        resetColor(JPbtn_home);
        resetColor(JPbtn_Devoluciones);
        resetColor(JPbtn_Libros);
        resetColor(JPbtn_Reportes);
        
        // Abrir sección
        Usuarios b1 = new Usuarios();
        b1.setSize(750, 430);
        b1.setLocation(0,0);
        
        JP_content.removeAll();
        JP_content.add(b1, BorderLayout.CENTER);
        JP_content.revalidate();
        JP_content.repaint();
    }//GEN-LAST:event_JPbtn_UsuariosMousePressed

    private void JPbtn_LibrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_LibrosMouseEntered
         setColor(JPbtn_Libros);
    }//GEN-LAST:event_JPbtn_LibrosMouseEntered

    private void JPbtn_LibrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_LibrosMouseExited
        resetColor(JPbtn_Libros);
    }//GEN-LAST:event_JPbtn_LibrosMouseExited

    private void JPbtn_LibrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_LibrosMousePressed
        setColor(JPbtn_Libros);
        resetColor(JPbtn_Prestamos);
        resetColor(JPbtn_home);
        resetColor(JPbtn_Devoluciones);
        resetColor(JPbtn_Usuarios);
        resetColor(JPbtn_Reportes);
        
        Libros b1 = new Libros();
        b1.setSize(750, 430);
        b1.setLocation(0,0);
        
        JP_content.removeAll();
        JP_content.add(b1, BorderLayout.CENTER);
        JP_content.revalidate();
        JP_content.repaint();
    }//GEN-LAST:event_JPbtn_LibrosMousePressed

    private void JPbtn_ReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_ReportesMouseEntered
         setColor(JPbtn_Reportes);
    }//GEN-LAST:event_JPbtn_ReportesMouseEntered

    private void JPbtn_ReportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_ReportesMouseExited
        resetColor(JPbtn_Reportes);
    }//GEN-LAST:event_JPbtn_ReportesMouseExited

    private void JPbtn_ReportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPbtn_ReportesMousePressed
        setColor(JPbtn_Reportes);
        resetColor(JPbtn_Prestamos);
        resetColor(JPbtn_home);
        resetColor(JPbtn_Devoluciones);
        resetColor(JPbtn_Usuarios);
        resetColor(JPbtn_Libros);
        
        Reporte b1 = new Reporte();
        b1.setSize(750, 430);
        b1.setLocation(0,0);
        
        JP_content.removeAll();
        JP_content.add(b1, BorderLayout.CENTER);
        JP_content.revalidate();
        JP_content.repaint();
    }//GEN-LAST:event_JPbtn_ReportesMousePressed

    private void TituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_TituloMousePressed

    private void TituloMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_TituloMouseDragged

    private void JP_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_exitMouseEntered
        JP_exit.setBackground(new Color(204,0,0));
        exit.setForeground(Color.white);
    }//GEN-LAST:event_JP_exitMouseEntered

    private void JP_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JP_exitMouseExited
        JP_exit.setBackground(new Color(242,242,242));
        exit.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_JP_exitMouseExited

    void setColor(JPanel panel){
        panel.setBackground(new Color(85,55,118));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(63,43,100));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_Header;
    public static javax.swing.JPanel JP_content;
    private javax.swing.JPanel JP_exit;
    private javax.swing.JPanel JPbtn_Devoluciones;
    private javax.swing.JPanel JPbtn_Libros;
    private javax.swing.JPanel JPbtn_Prestamos;
    private javax.swing.JPanel JPbtn_Reportes;
    private javax.swing.JPanel JPbtn_Usuarios;
    private javax.swing.JPanel JPbtn_home;
    private javax.swing.JPanel Titulo;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
