/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package codigo;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author juanp
 */
public class Prestamos extends javax.swing.JPanel {

    /**
     * Creates new form Prestamos
     */
    public Prestamos() {
        initComponents();

        //rsscalelabel.RSScaleLabel.setScaleLabel(jLabel2, "src/imagenes/vector-pile-of-color-cartoon-style-books.jpg");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        book_id = new javax.swing.JTextField();
        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        idUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        Title = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(750, 430));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        book_id.setForeground(new java.awt.Color(102, 102, 102));
        book_id.setText("Ingrese el id del Libro a prestar");
        book_id.setBorder(null);
        book_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                book_idMousePressed(evt);
            }
        });
        book_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_idActionPerformed(evt);
            }
        });
        add(book_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 260, 30));

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text1.setText("Libro ID");
        add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text2.setText("Id del usuario");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        idUsuario.setForeground(new java.awt.Color(102, 102, 102));
        idUsuario.setText("Ingrese el id del usuario");
        idUsuario.setBorder(null);
        idUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idUsuarioMousePressed(evt);
            }
        });
        add(idUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 260, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prestamo2-removebg.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(270, 270));
        jLabel2.setMinimumSize(new java.awt.Dimension(270, 270));
        jLabel2.setPreferredSize(new java.awt.Dimension(270, 270));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 270, 280));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 10, 350));

        jButton2.setBackground(new java.awt.Color(54, 33, 89));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reservar");
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 90, 40));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Prestamo de Libro");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void book_idMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book_idMousePressed
        if(book_id.getText().equals("Ingrese el id del Libro a prestar"))
        book_id.setText("");
        if(idUsuario.getText().equals("") || idUsuario.getText() == null || idUsuario.getText().equals(" "))
        idUsuario.setText("Ingrese el id del usuario");
    }//GEN-LAST:event_book_idMousePressed

    private void book_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_book_idActionPerformed

    private void idUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idUsuarioMousePressed
        if(idUsuario.getText().equals("Ingrese el id del usuario"))
        idUsuario.setText("");
        if(book_id.getText().equals("") || book_id.getText() == null || book_id.getText().equals(" "))
        book_id.setText("Ingrese el id del Libro a prestar");
    }//GEN-LAST:event_idUsuarioMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField book_id;
    private javax.swing.JTextField idUsuario;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
