/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package codigo;

import static codigo.Home.JP_content;
import java.awt.BorderLayout;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author juanp
 */
public class upLibros extends javax.swing.JPanel {

    /**
     * Creates new form upLibros
     */
    public upLibros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text6 = new javax.swing.JLabel();
        Text7 = new javax.swing.JLabel();
        Text8 = new javax.swing.JLabel();
        Text9 = new javax.swing.JLabel();
        Text10 = new javax.swing.JLabel();
        Text14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtEjemplares = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtEdicion = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Nuevo Libro");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Título");
        jPanel1.add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Año de publicación");
        jPanel1.add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Autor");
        jPanel1.add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("Categoría");
        jPanel1.add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        Text10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text10.setText("Edición");
        jPanel1.add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        Text14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text14.setText("Ejemplares (stock)");
        jPanel1.add(Text14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 10, 250));
        jPanel1.add(txtEjemplares, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 240, -1));
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 240, -1));
        jPanel1.add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, -1));
        jPanel1.add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, -1));
        jPanel1.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 240, -1));
        jPanel1.add(txtEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 240, -1));

        btnVolver.setBackground(new java.awt.Color(54, 33, 89));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorderPainted(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 90, 40));

        btnAñadir.setBackground(new java.awt.Color(54, 33, 89));
        btnAñadir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("Añadir");
        btnAñadir.setBorderPainted(false);
        btnAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 90, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // Abrir sección
        Libros p1 = new Libros();
        p1.setSize(750, 430);
        p1.setLocation(0,0);

        JP_content.removeAll();
        JP_content.add(p1, BorderLayout.CENTER);
        JP_content.revalidate();
        JP_content.repaint();        
    }//GEN-LAST:event_btnVolverActionPerformed

    private void limpiar(){
        txtTitulo.setText("");
        txtAutor.setText("");
        txtAño.setText("");
        txtAño.setText("");        
        txtCategoria.setText("");
        txtEjemplares.setText("");
    }
    
    
     /*
        String salida="";
        try{
            Statement sql = Conexion.getConnection().createStatement();
            String consulta = "SELECT name FROM master.dbo.sysdatabases";
        
            ResultSet resultado = sql.executeQuery(consulta);
        
            while(resultado.next()){
                 salida+=resultado.getString(1) + "\n";   
            }
            JOptionPane.showMessageDialog(null, salida);
        catch(){
        
        }
        */
    
    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        Connection con = null;
        PreparedStatement prSt = null;
        ResultSet rs = null;
       
        String salida="";
       
        try{
            String titulo = txtTitulo.getText(); //IdTitulo
            
            /*
            String autor = txtAutor.getText(); //IdAutor
            int año = Integer.parseInt(txtAño.getText());
            short edicion = Short.parseShort(txtEdicion.getText());
            String categoria = txtCategoria.getText();//IdCategoria
            short ejemplares = Short.parseShort(txtEjemplares.getText());
            */
            
            con = Conexion.getConnection();
            String query = "SELECT * FROM Titulos WHERE Titulo = ?";
            prSt = con.prepareStatement(query);
            prSt.setString(1, titulo);
            rs = prSt.executeQuery();
            while(rs.next()){
                JOptionPane.showMessageDialog(null, rs.getString("Titulo"));
            }
            rs.close();
           
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error: " + ex.toString());
        }
        
        /*
        String titulo = txtTitulo.getText(); //IdTitulo
        String autor = txtAutor.getText(); //IdAutor
        int año = Integer.parseInt(txtAño.getText());
        short edicion = Short.parseShort(txtEdicion.getText());
        String categoria = txtCategoria.getText();//IdCategoria
        short ejemplares = Short.parseShort(txtEjemplares.getText());
        
        try{
            Connection con = Conexion.getConnection();
            PreparedStatement ps = con.prepareStatement("INSERT INTO Libros (IdTitulo,IdAutor,Año,IdCategoria, Edicion, Ejemplares, Disponibles) VALUES (?,?,?,?,?,?,?)");
            ps.setString(1, titulo);
            ps.setString(2, autor);
            ps.setInt(3, año);
            ps.setShort(4, edicion);
            ps.setString(5, categoria);
            ps.setShort(6, ejemplares);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro añadido exitosamente");
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error: " + ex.toString());
        }
        */
        
        
        
        /*
        


            
            Statement sql = Conexion.getConnection().createStatement();
            
            //Busco si existe un libro con el titulo ingresado
            String consulta = "SELECT * FROM Titulos "
                            + "WHERE Titulo = " + "'"+titulo+"'";
            
            //ResultSet resultado = sql.executeQuery(consulta);
                    //si ya existe titulo error else insert en TBALA
            
            if(resultado!=null){
                try{
                    //Connection con = Conexion.getConnection();
                    PreparedStatement ps = con.prepareStatement("INSERT INTO Titulos (IdTitulo,Titulo) VALUES (?,?)");
                    
                    //sIdTitulo=SELECT MAX(IdTitulo) FROM Titulos;
                    
                    String consultaMax = "SELECT MAX(IdTitulo) FROM Titulos";
                    resultado = sql.executeQuery(consultaMax);
                    
                    
                    int val =  ((Number) resultado.getObject(1)).intValue();
                    val++;
                    ps.setInt(1, val);
                    ps.setString(2, titulo);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Registro añadido exitosamente");
                    limpiar();

                }catch(SQLException ex){
                    JOptionPane.showMessageDialog(null, "Error: " + ex.toString());
                }
                
                while(resultado.next()){
                    salida+=resultado.getString(1) + "\n";   
                }
                JOptionPane.showMessageDialog(null, salida);
            }else{
                JOptionPane.showMessageDialog(null, "Error el libro con el titulo " + titulo +" ya existe.");
            }
        
        
        */
    }//GEN-LAST:event_btnAñadirActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text14;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtEjemplares;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
