/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package codigo;

import static codigo.Home.JP_content;
import java.awt.BorderLayout;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author juanp
 */
public class upLibros extends javax.swing.JPanel {

    int idus;
    boolean edit;
    
    public upLibros() {
        initComponents();
    }
    
    public upLibros(int l_idLibro, String l_titulo, String l_autor, int l_año, String l_categoria, String l_edicion, String l_ejemplares) {
        initComponents();
        idus = l_idLibro;
        txtTitulo.setText(l_titulo);
        txtAutor.setText(l_autor);
        jyear.setYear(l_año);
        txtEdicion.setText(l_edicion);
        txtCategoria.setText(l_categoria);
        txtEjemplares.setText(l_ejemplares);
        
        edit = true;
        Title.setText("Modificar Libro");
        btnAñadir.setText("Guardar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Text6 = new javax.swing.JLabel();
        Text7 = new javax.swing.JLabel();
        Text8 = new javax.swing.JLabel();
        Text9 = new javax.swing.JLabel();
        Text10 = new javax.swing.JLabel();
        Text14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtEjemplares = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtEdicion = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        JP_year = new javax.swing.JPanel();
        jyear = new com.toedter.calendar.JYearChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Nuevo Libro");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Título");
        jPanel1.add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Año de publicación");
        jPanel1.add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Autor");
        jPanel1.add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("Categoría");
        jPanel1.add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        Text10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text10.setText("Edición");
        jPanel1.add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        Text14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text14.setText("Ejemplares (stock)");
        jPanel1.add(Text14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 10, 250));
        jPanel1.add(txtEjemplares, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 240, -1));
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 240, -1));
        jPanel1.add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, -1));
        jPanel1.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 240, -1));
        jPanel1.add(txtEdicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 240, -1));

        btnVolver.setBackground(new java.awt.Color(54, 33, 89));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorderPainted(false);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 90, 40));

        btnAñadir.setBackground(new java.awt.Color(54, 33, 89));
        btnAñadir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("Añadir");
        btnAñadir.setBorderPainted(false);
        btnAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel1.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 90, 40));
        jPanel1.add(JP_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 110, 30));

        jyear.setDayChooser(null);
        jPanel1.add(jyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 240, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // Abrir sección
        Libros p1 = new Libros();
        p1.setSize(750, 430);
        p1.setLocation(0,0);

        JP_content.removeAll();
        JP_content.add(p1, BorderLayout.CENTER);
        JP_content.revalidate();
        JP_content.repaint();        
    }//GEN-LAST:event_btnVolverActionPerformed

    private void limpiar(){
        txtTitulo.setText("");
        txtAutor.setText("");
        txtEdicion.setText("");
        txtCategoria.setText("");
        txtEjemplares.setText("");
    }
    
          
    
    
    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        Connection con = null;
        PreparedStatement prSt = null;
        String query;

        String titulo = txtTitulo.getText();
        String autor = txtAutor.getText();
        String categoria = txtCategoria.getText();
        int year = jyear.getYear();
        short edicion = Short.parseShort(txtEdicion.getText());
        short ejemplares = Short.parseShort(txtEjemplares.getText());
       
        int idTitulo = verificar(titulo,"Titulos","Titulo");
        int idAutor = verificar(autor,"Autores","Autor");
        int idCategoria = verificar(categoria,"Categorias","Categoria");
        
        if(!edit){
            //nuevo libro
            try{
                con = Conexion.getConnection();
                query = "INSERT INTO Libros (IdTitulo,IdAutor,Año,IdCategoria, Edicion, Ejemplares, Disponibles) VALUES (?,?,?,?,?,?,?)";
                prSt = con.prepareStatement(query);
                prSt.setInt(1, idTitulo);
                prSt.setInt(2, idAutor);
                prSt.setInt(3, year);
                prSt.setInt(4,idCategoria);
                prSt.setShort(5, edicion);
                prSt.setShort(6, ejemplares);
                prSt.setShort(7, ejemplares);
                prSt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Libro añadido exitosamente");
                limpiar();

            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Error: " + ex.toString());
            }
        }else{
            //editar usuario
            try{ 
                con = Conexion.getConnection();
                query = "UPDATE Libros SET IdTitulo = '" + idTitulo +"' , IdAutor= '" + idAutor +"', Año = '" + year +"' , IdCategoria= '" + idCategoria +"', Edicion = '" + edicion +"' , Ejemplares= '" + ejemplares +"'"
                        + "WHERE IdLibro = ?";
                prSt = con.prepareStatement(query);
                prSt.setInt(1, idus);
                prSt.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "¡Libro editado! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                Libros p1 = new Libros();
                p1.setSize(750, 430);
                p1.setLocation(0,0);

                JP_content.removeAll();
                JP_content.add(p1, BorderLayout.CENTER);
                JP_content.revalidate();
                JP_content.repaint();  
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Error: " + ex.toString());
            }
        } 
  
    }//GEN-LAST:event_btnAñadirActionPerformed
    
    private int verificar(String variable, String nombreTabla, String nombreCampo){
        Connection con = null;
        PreparedStatement prSt = null;
        ResultSet rs = null;
        boolean resultado = false;
        int id=-1;
        
        try{
            con = Conexion.getConnection();
            String query = "SELECT * FROM "+ nombreTabla+ " WHERE "+ nombreCampo+ " = ?";
            prSt = con.prepareStatement(query);
            prSt.setString(1, variable);
            rs = prSt.executeQuery();
            while(rs.next()){
                //JOptionPane.showMessageDialog(null, rs.getString(1));
                id = rs.getInt(1);
                resultado= true;
                break;
            }

            if(!resultado){
                query = "INSERT INTO "+ nombreTabla+ " ("+ nombreCampo+") VALUES (?)";
                prSt = con.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
                prSt.setString(1, variable);
                prSt.executeUpdate();
                
                ResultSet generatedKeys = prSt.getGeneratedKeys();
                if (generatedKeys.next()) {
                   id=generatedKeys.getInt(1);
                }
            }
            //rs.close();
        
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error: " + ex.toString());
        }
        
        return id;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_year;
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text14;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private com.toedter.calendar.JYearChooser jyear;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtEdicion;
    private javax.swing.JTextField txtEjemplares;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
