/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package codigo;

import static codigo.Home.JP_content;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author juanp
 */
public class Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPbody = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        usrnm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(750, 430));
        setMinimumSize(new java.awt.Dimension(710, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPbody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Usuarios");
        JPbody.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        usrnm.setForeground(new java.awt.Color(102, 102, 102));
        usrnm.setText("Ingrese el nombre de usuario a buscar");
        usrnm.setBorder(null);
        usrnm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usrnmMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                usrnmMouseReleased(evt);
            }
        });
        JPbody.add(usrnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 530, 30));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Primer nombre", "Segundo nombre", "Primer apellido", "Segundo apellido", "Domicilio", "Telefono", "Devoluciones Extratemporales"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Short.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        JPbody.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 660, 240));

        btnActualizar.setBackground(new java.awt.Color(54, 33, 89));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        JPbody.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 100, 40));

        btnNuevo.setBackground(new java.awt.Color(54, 33, 89));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        JPbody.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 80, 40));

        btnEliminar.setBackground(new java.awt.Color(54, 33, 89));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        JPbody.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 80, 40));

        btnBuscar.setBackground(new java.awt.Color(54, 33, 89));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorderPainted(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setDefaultCapable(false);
        JPbody.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 70, 30));

        add(JPbody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void usrnmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usrnmMousePressed
        if(usrnm.getText().equals("Ingrese el nombre de usuario a buscar"))
        usrnm.setText("");
    }//GEN-LAST:event_usrnmMousePressed

    private void usrnmMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usrnmMouseReleased
        //nothing
    }//GEN-LAST:event_usrnmMouseReleased

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        /*
        String primerNombre = txtPrimerNombre.getText(); 
        String segundoNombre = txtSegundoNombre.getText();
        String primerApellido = txtPrimerApellido.getText(); 
        String segundoApellido = txtSegundoApellido.getText();
        String Direccion = txtDomicilio.getText(); 
        int Telefono = Integer.parseInt(txtTelefono.getText());
        
        try{
            Connection con = Conexion.getConnection();
            PreparedStatement ps = con.prepareStatement("INSERT INTO Usuarios (PrimerNombre,SegundoNombre,PrimerApellido, SegundoApellido, Direccion, Telefono, DevolucionesExtratemporales) VALUES (?,?,?,?,?,?,?)");
            ps.setString(1, primerNombre);
            ps.setString(2, segundoNombre);
            ps.setString(3, primerApellido);
            ps.setString(4, segundoApellido);
            ps.setString(5, Direccion);
            ps.setInt(6, Telefono);
            ps.setShort(7, (short)0);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Usuario añadido exitosamente");
            limpiar();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error: " + ex.toString());
        }
        */
        
        PreparedStatement ps;
        ResultSet rs; 
        
        try {
            int idcell = tablaUsuarios.getSelectedRow();
            if(idcell <= -1){
                javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el libro a editar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                
                Connection con = Conexion.getConnection();
                ps = con.prepareStatement("select * from Usuarios");
                rs = ps.executeQuery();
                
                //Statement stm = reg.createStatement();
                //ResultSet counter = stm.executeQuery("SELECT * FROM `books`");

                //stm ->ps
                //reg -> con
                //stm -> ps
                //counter -> rs
                
                int count = 0;
                while(rs.next()){
                    count++;
                }

                String list[][] = new String[count][12];
                int i = 0;
                ResultSet re = ps.executeQuery("SELECT * FROM Usuarios");
                while(re.next()){
                    list[i][0] = re.getString("IdUsuario");
                    list[i][1] = re.getString("PrimerNombre");
                    list[i][2] = re.getString("SegundoNombre");
                    list[i][3] = re.getString("PrimerApellido");
                    list[i][4] = re.getString("SegundoApellido");
                    list[i][5] = re.getString("Direccion");
                    list[i][6] = re.getString("Telefono");
                    list[i][7] = re.getString("DevolucionesExtratemporales");
                    i++;
                }
                String id = list[idcell][0];
                if(id == null || id.equals("")){
                    javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar el libro a editar. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    String id_Usuario = ""+list[idcell][0];
                    String primer_Nombre = list[idcell][1];
                    String segundo_Nombre = list[idcell][2];
                    String primer_Apellido = list[idcell][3];
                    String segundo_Apellido = list[idcell][4];
                    String direccion = list[idcell][5];
                    String telefono = list[idcell][6];
                    String devolucionesExtratemporales = list[idcell][7];
                 
                    //upUsers us = new upUsers(id_Usuario, primer_Nombre, segundo_Nombre, primer_Apellido, segundo_Apellido, direccion, telefono, devolucionesExtratemporales);
                    //us.setSize(750, 430);
                    //us.setLocation(5, 5);

                    //JP_content.removeAll();
                    //JP_content.add(us, BorderLayout.CENTER);
                    //JP_content.revalidate();
                    //JP_content.repaint();
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.toString());
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // Abrir sección
        upUsers p1 = new upUsers();
        p1.setSize(750, 430);
        p1.setLocation(0,0);

        JP_content.removeAll();
        JP_content.add(p1, BorderLayout.CENTER);
        JP_content.revalidate();
        JP_content.repaint();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
       /*
        try{
            PreparedStatement ps;
            ResultSet rs;
            int fila = tablaUsuarios.getSelectedRow();
            int id = Integer.parseInt(tablaUsuarios.getValueAt(fila, 0).toString());
           
            Connection con = Conexion.getConnection();
           
            ps = con.prepareStatement("INSERT INTO Usuarios (PrimerNombre,SegundoNombre,PrimerApellido, SegundoApellido, Direccion, Telefono, DevolucionesExtratemporales) VALUES (?,?,?,?,?,?,?)");
            ps.setString(1, primerNombre);
            ps.setString(2, segundoNombre);
            ps.setString(3, primerApellido);
            ps.setString(4, segundoApellido);
            ps.setString(5, Direccion);
            ps.setInt(6, Telefono);
            ps.setShort(7, (short)0);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Usuario añadido exitosamente");
           
           
       }catch(){
       
       }
    */
    }//GEN-LAST:event_tablaUsuariosMouseClicked
    
    private void cargarTabla(){
        DefaultTableModel modeloTabla = (DefaultTableModel)tablaUsuarios.getModel();
        modeloTabla.setRowCount(0);
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        int[] anchos = {10,50,50,50,50,50,50,50};
        for(int i=0; i<tablaUsuarios.getColumnCount();i++){
            tablaUsuarios.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        
        try{
            Connection con = Conexion.getConnection();
            ps = con.prepareStatement("select * from Usuarios");
            rs = ps.executeQuery();
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[columnas];
                for(int indice = 0; indice <columnas; indice++){
                    fila[indice] = rs.getObject(indice +1);
                }
                modeloTabla.addRow(fila);
                
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error: " + ex.toString());
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPbody;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField usrnm;
    // End of variables declaration//GEN-END:variables
}
